VEuPathDB/vdi-service

schemata/dataset-manifest.schema.json

JSON schema definition for a dataset's `manifest.json` file.
Example JSON:
```json
{
"inputFiles": [
"my-dog.jpg",
"w2.pdf",
"birthday.mp4"
],
"dataFiles": [
"001.biom",
"002.biom",
]
}
```

Add manifest json schema

---

schemata/dataset-metadata.schema.json

The following JSON examples are valid against this schema.
**Common Usecase**
```json
{
"type": {
"name": "BIOM",
"version": "1.0"
},
"projects": [
"PlasmoDB",
"VectorBase"
],
"owner": "123456789",
"name": "My Okay Dataset",
"summary": "It's just okay",
"description": "Nothing special about it.",
"dependencies": [
{
"resourceIdentifier": "something1",
"resourceVersion": "something1",
"resourceDisplayName": "something1"
},
{
"resourceIdentifier": "something2",
"resourceVersion": "something2",
"resourceDisplayName": "something2"
}
]
}
```
**Minimum Required**
```json
{
"type": {
"name": "A",
"version": "B"
},
"projects": [
"C"
],
"owner": "D",
"name": "E"
}
```

add schema for dataset meta.json

---

util-handler-server/src/main/kotlin/vdi/util/script/ScriptExecutor.kt
util-handler-server/src/main/kotlin/vdi/util/script/ScriptExecutorImpl.kt
util-handler-server/src/main/kotlin/vdi/util/script/ScriptProcess.kt
util-handler-server/src/main/kotlin/vdi/util/script/ScriptProcessImpl.kt

This PR adds 2 interfaces and implementations of types that wrap Java's `ProcessBuilder` and `Process` types to both abstract away common logic that all script execution points will use and to allow unit testing the code that calls the handler plugin scripts.
The types are:
Wraps Java's `ProcessBuilder` type with a mockable interface and a call method tailored to our script execution use case.
Wraps Java's `Process` type with a mockable interface including methods tailored for our script execution use case.

Script execution wrapper.

---

modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEvent.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventAction.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventCreateSubAction.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventDeleteSubAction.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventRecord.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventRecordS3.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventRecordS3Bucket.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventRecordS3Object.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventRecordSource.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventSubAction.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventType.kt
modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventUserIdentity.kt

Model objects for the bucket events: `s3:ObjectCreated:*` and `s3:ObjectRemoved:*`.
Tested by deserializing events from MinIO
<details>
<summary>Example Create Event</summary>
```json
{
"EventName": "s3:ObjectCreated:Put",
"Key": "some-other-bucket/minio.png",
"Records": [
{
"eventVersion": "2.0",
"eventSource": "minio:s3",
"awsRegion": "",
"eventTime": "2023-02-28T12:46:17.934Z",
"eventName": "s3:ObjectCreated:Put",
"userIdentity": {
"principalId": "someToken"
},
"requestParameters": {
"principalId": "someToken",
"region": "",
"sourceIPAddress": "127.0.0.1"
},
"responseElements": {
"content-length": "0",
"x-amz-request-id": "1747FDBDD1E65B89",
"x-minio-deployment-id": "f143f7ea-b0c8-4c67-bd9d-452d1ec89cca",
"x-minio-origin-endpoint": "http://172.24.0.5:9000"
},
"s3": {
"s3SchemaVersion": …
```

Bucket Event Modelling

---

modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/Resources.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/server/controllers/ControllerBase.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/server/controllers/VDIDatasetByIDEndpointsController.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/server/controllers/VDIDatasetSharePutController.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/server/middleware/AuthFilter.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/get-dataset-by-id.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/shares/put-share-offer.kt

Adds a general method of authentication using an admin token/secret-key that may be used on controller methods annotated with a new `AllowAdminAuth` annotation.
The endpoints that now allow admin auth (and previously didn't) are:
* GET dataset details
* PUT dataset share offer
* PUT dataset share receipt

Add admin auth to target endpoints

---

components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/AppDBTransaction.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/AppDBTransactionImpl.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/delete-dataset-meta.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/insert-dataset-meta.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/update-dataset-meta.kt
modules/reconciler/src/main/kotlin/org/veupathdb/vdi/lib/reconciler/AppDBTarget.kt
modules/update-meta-trigger-handler/src/main/kotlin/vdi/module/handler/meta/triggers/UpdateMetaTriggerHandlerImpl.kt
schemata/ddl/oracle.sql

We have added a new control table to the application database schema called `dataset_meta`, this PR adds methods to insert, update, and delete dataset_meta records.

App db `dataset_meta`

---

modules/soft-delete-trigger-handler/src/main/kotlin/vdi/module/handler/delete/soft/SoftDeleteTriggerHandlerImpl.kt

If we fail to uninstall from the app dbs, we never update the postgres record to deleted.

Write to postgres after app dbs

---

modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/delete-dataset-by-id.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/update-dataset-by-id.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/shares/put-share-offer.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/shares/put-share-receipt.kt

Change the way write actions are handled to immediately update the internal postgres instance instead of waiting for the event to come back from minio.  This is to support a synchronous seeming API for the client.

Short circuit write actions to the internal postgres.

---

modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/create-dataset.kt

Previously we did not check this and returned a 500 down the line if the app db was unrecognized.

Reject requests targetting an AppDB that is not registered.

---

components/pruner/src/main/kotlin/vdi/component/pruner/Pruner.kt
modules/soft-delete-trigger-handler/src/main/kotlin/vdi/module/handler/delete/soft/SoftDeleteTriggerHandlerImpl.kt

Fixes:
* Dataset uninstaller (soft delete module) should no longer attempt to delete datasets that weren't imported.
* Dataset pruner should no longer fail for a missed table in its deletes.
Resolves #145

Dataset deletion fixes

---

components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/AppDB.kt
components/dataset-reinstaller/src/main/kotlin/vdi/component/reinstaller/DatasetReinstaller.kt
components/install-cleanup/src/main/kotlin/vdi/component/install_cleanup/InstallCleaner.kt
components/pruner/src/main/kotlin/vdi/component/pruner/Pruner.kt
modules/install-trigger-handler/src/main/kotlin/vdi/module/handler/install/data/InstallDataTriggerHandlerImpl.kt
modules/reconciler/src/main/kotlin/org/veupathdb/vdi/lib/reconciler/AppDBTarget.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/list-broken.kt
modules/share-trigger-handler/src/main/kotlin/vdi/module/handler/share/trigger/ShareTriggerHandlerImpl.kt
modules/soft-delete-trigger-handler/src/main/kotlin/vdi/module/handler/delete/soft/SoftDeleteTriggerHandlerImpl.kt
modules/update-meta-trigger-handler/src/main/kotlin/vdi/module/handler/meta/triggers/UpdateMetaTriggerHandlerImpl.kt

Previously on reconciler or reinstaller runs, if a dataset was targetting a project that has been disabled, it would throw an exception.  The exceptions were harmless but noisy, this PR adjusts the trigger handlers to log a message instead of throwing an exception when a dataset's target project is no longer enabled.

Handle the case where a project with datasets is disabled

---

modules/event-router/src/main/kotlin/vdi/module/events/routing/model/MinIOEventRecordS3Object.kt

Because versioning is enabled in dev MinIO, the versionId field is being populated. This PR supports parsing that field, though it is not used in any way currently as objects should never be overwritten with differing contents.

Add version ID to MinIO s3 event object

---

components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/model/DatasetInstallMessage.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/insert-dataset-install-message.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/select-dataset-install-message.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/select-dataset-install-messages.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/update-dataset-install-message.kt

Adds a timestamp field to the dataset message record type to match the addition of the field in the vdi app db control tables.

add timestamp to install messages

---

components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/select-all-sync-control.kt
components/cache-db/src/main/kotlin/org/veupathdb/vdi/lib/db/cache/sql/select/select-all-sync-control.kt
components/metrics/src/main/kotlin/vdi/component/metrics/Metrics.kt
components/s3/src/main/kotlin/org/veupathdb/vdi/lib/s3/datasets/EagerlyLoadedDatasetDirectory.kt
components/s3/src/main/kotlin/org/veupathdb/vdi/lib/s3/datasets/exception/MalformedDatasetException.kt
modules/reconciler/src/main/kotlin/org/veupathdb/vdi/lib/reconciler/ReconcilerImpl.kt
modules/reconciler/src/main/kotlin/org/veupathdb/vdi/lib/reconciler/ReconcilerInstance.kt
modules/reconciler/src/test/kotlin/org/veupathdb/vdi/lib/reconciler/ReconcilerTest.kt
src/main/resources/log4j2.yml

Ensure comparisons are in sync across MinIO, database and comparisons in code.
The MinIO list objects results are sorted ignoring case, which is a little unusual as it's not in accordance with UTF-8 ordering. Kotlin, Java, Oracle and Postgres all use UTF-8 sorting. I updated all sorts to be case-insensitive.
I also added a malformed dataset exception that gets gracefully handled in the reconciler.

Remove case sensitivity from comparisons to be compatible with MinIO sorts

---

components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/AppDBAccessor.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/AppDBAccessorImpl.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/AppDBTransactionImpl.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/select-all-sync-control.kt
components/cache-db/src/main/kotlin/org/veupathdb/vdi/lib/db/cache/CacheDB.kt
components/cache-db/src/main/kotlin/org/veupathdb/vdi/lib/db/cache/sql/select/select-all-sync-control.kt
components/metrics/src/main/kotlin/vdi/component/metrics/Metrics.kt
components/s3/build.gradle.kts
components/s3/src/main/kotlin/org/veupathdb/vdi/lib/s3/datasets/DatasetManager.kt
modules/reconciler/src/main/kotlin/org/veupathdb/vdi/lib/reconciler/AppDBTarget.kt
modules/reconciler/src/main/kotlin/org/veupathdb/vdi/lib/reconciler/CacheDBTarget.kt
modules/reconciler/src/main/kotlin/org/veupathdb/vdi/lib/reconciler/ReconcilerInstance.kt
modules/reconciler/src/main/kotlin/org/veupathdb/vdi/lib/reconciler/ReconcilerTarget.kt
modules/reconciler/src/test/kotlin/org/veupathdb/vdi/lib/reconciler/ReconcilerTest.kt
platform/build.gradle.kts

* Fixed the sort to avoid deleting large swaths of data
* This was due to the owner ID not being included when comparing the streams in-memory

Fix the sort to use owner ID

---

components/s3/build.gradle.kts
components/s3/src/main/kotlin/org/veupathdb/vdi/lib/s3/datasets/DatasetManager.kt
components/s3/src/test/kotlin/org/veupathdb/vdi/lib/s3/datasets/paths/DatasetManagerTest.kt
components/s3/src/test/kotlin/org/veupathdb/vdi/lib/s3/datasets/paths/IndexKtTest.kt
components/s3/src/test/kotlin/org/veupathdb/vdi/lib/s3/datasets/paths/S3PathsTest.kt

Fixing the malformed dataset handling in stream API. This change attempts to make the stream API resilient to malformed datasets, logging them and noting them along the way.

Fix dataset manager streaming API when datasets are malformed

---

components/metrics/src/main/kotlin/vdi/component/metrics/Metrics.kt
modules/import-trigger-handler/src/main/kotlin/vdi/module/handler/imports/triggers/ImportTriggerHandlerImpl.kt
modules/rest-service/build.gradle.kts
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/create-dataset.kt

Moves the portion of the upload process where the dataset files are (re)packed and uploaded to MinIO into a separate thread as part of a threadpool.

Async Dataset Uploads

---

components/cache-db/src/main/kotlin/org/veupathdb/vdi/lib/db/cache/model/DatasetShare.kt
components/cache-db/src/main/kotlin/org/veupathdb/vdi/lib/db/cache/sql/select/select-dataset-shares.kt
docker-compose.dev.yml
modules/event-router/src/main/kotlin/vdi/module/events/routing/EventRouterImpl.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/get-dataset-by-id.kt
modules/share-trigger-handler/src/main/kotlin/vdi/module/handler/share/trigger/ShareTriggerHandlerImpl.kt
modules/update-meta-trigger-handler/src/main/kotlin/vdi/module/handler/meta/triggers/UpdateMetaTriggerHandlerImpl.kt

The initial implementation of the share event handler only checked the sync control record in the internal postgres cache database to determine whether shares were out of sync.  This lead to issues where datasets were removed/readded or altered in the target database but their shares were no longer synchronized because the share event handler never checked the target database's sync control record.
This rewrite attempts to resolve that by having the handler check every one of the dataset's target projects' sync control records to ensure the shares are up to date regardless of whether the postgres cache db's sync control record is up to date.
---
In addition to the above changes, an unrelated share issue was located in the user dataset details endpoint call tree where datasets with a share …

Share event handler rewrite.

---

components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/insert-dataset.kt
components/cache-db/src/main/kotlin/org/veupathdb/vdi/lib/db/cache/sql/insert/insert-dataset.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/generated/model/x-DatasetTypeInfo.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/server/controllers/VDIDatasetFilesController.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/server/controllers/VDIUsersController.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/admin/list-all-datasets.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/create-dataset.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/list-broken.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/shares/get-shares.kt

Ensure the dataset type name is in lowercase when:
1. Returned to the API client
2. Written to MinIO
3. Written to the internal postgres cache DB
4. Written to the target app DBs
Preexisting datasets that have type names with capitalization can stay as they are.  Their type name will be converted to lowercase when going out the door.
Resolves #187

Lowercase dataset type name

---

components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/AppDBTransaction.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/AppDBTransactionImpl.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/model/DatasetRecord.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/model/DeleteFlag.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/insert-dataset.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/select-dataset.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/select-datasets-by-install-status.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/update-dataset-deleted-flag.kt
components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/sql/update-dataset.kt
components/cache-db/src/main/kotlin/org/veupathdb/vdi/lib/db/cache/model/DeletedDataset.kt
components/cache-db/src/main/kotlin/org/veupathdb/vdi/lib/db/cache/sql/select/select-deleted-datasets.kt
components/pruner/src/main/kotlin/vdi/component/pruner/Pruner.kt
modules/import-trigger-handler/src/main/kotlin/vdi/module/handler/imports/triggers/ImportTriggerHandlerImpl.kt
modules/install-trigger-handler/src/main/kotlin/vdi/module/handler/install/data/InstallDataTriggerHandlerImpl.kt
modules/soft-delete-trigger-handler/src/main/kotlin/vdi/module/handler/delete/soft/SoftDeleteTriggerHandlerImpl.kt
modules/update-meta-trigger-handler/src/main/kotlin/vdi/module/handler/meta/triggers/UpdateMetaTriggerHandlerImpl.kt

* Changes the usage of the app db `is_deleted` field to be a 3-state enum value rather than a boolean flag.
* Updates the dataset soft-delete/uninstallation lane to:
* Always update the deletion flag in the internal postgres database regardless of whether the app db uninstall(s) succeeded.
* Update the `is_deleted` flag in the target app database(s) to a new value that indicates a delete was attempted or is in progress.  This value will hide the dataset from the dataset availability view in the app database(s)
* On successful uninstall, update the `is_deleted` flag in the target app database to a new value that indicates the delete succeeded.  This value will also hide the dataset from the dataset availability view in the app database(s)
* Updated the pruner to check all dataset install …

Dataset Uninstall and Pruning Fix

---

components/dataset-reinstaller/src/main/kotlin/vdi/component/reinstaller/DatasetReinstaller.kt
modules/dataset-reinstaller/src/main/kotlin/vdi/module/reinstaller/DatasetReinstallerImpl.kt
modules/install-trigger-handler/src/main/kotlin/vdi/module/handler/install/data/InstallDataTriggerHandlerImpl.kt
modules/update-meta-trigger-handler/src/main/kotlin/vdi/module/handler/meta/triggers/UpdateMetaTriggerHandlerImpl.kt

* Logging improvements
* Run dataset reinstaller on startup
* Always update data sync timestamp in app db even if install fails
* Fix bug where meta sync timestamp in app db wasn't being updated at all

Sync fixes and reinstaller run on startup.

---

components/cache-db/src/main/kotlin/org/veupathdb/vdi/lib/db/cache/sql/select/select-dataset-shares-list.kt
components/metrics/src/main/kotlin/vdi/component/metrics/Metrics.kt
modules/import-trigger-handler/src/main/kotlin/vdi/module/handler/imports/triggers/ImportTriggerHandlerImpl.kt
modules/install-trigger-handler/src/main/kotlin/vdi/module/handler/install/data/InstallDataTriggerHandlerImpl.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/list-datasets.kt
modules/share-trigger-handler/build.gradle.kts
modules/share-trigger-handler/src/main/kotlin/vdi/module/handler/share/trigger/ShareTriggerHandlerImpl.kt
modules/soft-delete-trigger-handler/src/main/kotlin/vdi/module/handler/delete/soft/SoftDeleteTriggerHandlerImpl.kt
modules/update-meta-trigger-handler/src/main/kotlin/vdi/module/handler/meta/triggers/UpdateMetaTriggerHandlerImpl.kt
platform/build.gradle.kts

Add metrics for WorkerPool queues.
Don't show shares for failed import datasets.

Add queue metrics and don't show shares if import failed

---

modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/server/controllers/VDIDatasetByIDEndpointsController.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/server/controllers/VDIDatasetFilesController.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/server/controllers/VDIDatasetSharePutController.kt
modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/server/controllers/VDIDatasetsAdminController.kt
platform/build.gradle.kts

* Use latest container core
* Fix annotations based on compatibility changes
1. Posted to `https://vdi-dev.local.apidb.org:8443/vdi-datasets` with my auth token
2. GET to `https://vdi-dev.local.apidb.org:8443/vdi-datasets/crjmaoxMfho` with admin token - Received 200
2. GET to `https://vdi-dev.local.apidb.org:8443/vdi-datasets/crjmaoxMfho` without admin token - Received 403
3. GET to `https://vdi-dev.local.apidb.org:8443/vdi-datasets/admin/failed-imports` with admin token - Received 200
4. GET to `https://vdi-dev.local.apidb.org:8443/vdi-datasets/admin/failed-imports` without admin token - Received 403

Use latest container core and adapt authenticated annotations

---

platform/build.gradle.kts

Using container-core with new multi-part file pojo library that uses buffered file output stream.

use latest container core

---

components/cache-db/src/main/kotlin/org/veupathdb/vdi/lib/db/cache/CacheDBTransactionImpl.kt
modules/reconciler/src/main/kotlin/org/veupathdb/vdi/lib/reconciler/ReconcilerInstance.kt
modules/reconciliation-event-handler/build.gradle.kts
modules/reconciliation-event-handler/src/main/kotlin/vdi/lane/reconciliation/DatasetReconciler.kt
modules/reconciliation-event-handler/src/test/kotlin/vdi/lane/reconciliation/DatasetReconcilerTest.kt

Sifting through the VDI logs I noticed that a reconciliation event for the dataset was being repeatedly fired by the reconciler and then it was being repeatedly processed by the reconciliation event handler.  Why the reconciler is firing an event for it is still unclear, but the reconciliation event handler should be ignoring it.
This PR addresses the above by:
1. Patch bug in dataset reconciler where dataset imports would be refired if the dataset import status was Invalid
2. Add additional logging to the reconciler to include the reason it is firing a sync event in the logs

Reconciliation Process Patches

---

components/module-core/src/main/kotlin/vdi/component/modules/AbstractJobExecutor.kt
components/module-core/src/main/kotlin/vdi/component/modules/AbstractVDIModule.kt
daemons/dataset-reinstaller/src/main/kotlin/vdi/daemon/reinstaller/DatasetReinstallerImpl.kt
daemons/dataset-reinstaller/src/main/kotlin/vdi/daemon/reinstaller/index.kt
daemons/event-router/src/main/kotlin/vdi/daemon/events/routing/EventRouterImpl.kt
daemons/event-router/src/main/kotlin/vdi/daemon/events/routing/index.kt
daemons/pruner/src/main/kotlin/vdi/daemon/pruner/PrunerModuleImpl.kt
daemons/pruner/src/main/kotlin/vdi/daemon/pruner/index.kt
daemons/reconciler/src/main/kotlin/vdi/daemon/reconciler/ReconcilerImpl.kt
daemons/reconciler/src/main/kotlin/vdi/daemon/reconciler/index.kt
lanes/hard-delete/src/main/kotlin/vdi/lane/delete/hard/HardDeleteTriggerHandlerImpl.kt
lanes/hard-delete/src/main/kotlin/vdi/lane/delete/hard/index.kt
lanes/import/src/main/kotlin/vdi/lane/imports/ImportTriggerHandlerImpl.kt
lanes/import/src/main/kotlin/vdi/lane/imports/index.kt
lanes/install/src/main/kotlin/vdi/lane/install/InstallDataTriggerHandlerImpl.kt
lanes/install/src/main/kotlin/vdi/lane/install/index.kt
lanes/reconciliation/src/main/kotlin/vdi/lane/reconciliation/ReconciliationEventHandlerImpl.kt
lanes/reconciliation/src/main/kotlin/vdi/lane/reconciliation/index.kt
lanes/sharing/src/main/kotlin/vdi/lane/sharing/ShareTriggerHandlerImpl.kt
lanes/sharing/src/main/kotlin/vdi/lane/sharing/index.kt
lanes/soft-delete/src/main/kotlin/vdi/lane/delete/soft/SoftDeleteTriggerHandlerImpl.kt
lanes/soft-delete/src/main/kotlin/vdi/lane/delete/soft/index.kt
lanes/update-meta/src/main/kotlin/vdi/lane/meta/UpdateMetaTriggerHandlerImpl.kt
lanes/update-meta/src/main/kotlin/vdi/lane/meta/index.kt
src/main/kotlin/vdi/bootstrap/Main.kt

1. Adds a new param to all coroutine based workers for a callback function that brings down the entire service.
2. Adds retries on rabbit connections when attempting to poll for messages

Add callback to enable coroutines to shutdown the service

---

service/rest-service/src/main/kotlin/org/veupathdb/service/vdi/service/datasets/delete-dataset-by-id.kt

To avoid leaving a dataset in a weird state where it isn't visible to the user but is never actually uninstalled.

put delete flag in minio before postgres

---

lib/async/src/main/kotlin/vdi/component/async/Trigger.kt

The issue wasn't actually a problem with the process, it was a misunderstanding of a debug feature that causes exceptions to be thrown under normal circumstances.

Fix exceptions on startup due to double locking on a mutex.

---

service/daemon/reconciler/src/main/kotlin/vdi/daemon/reconciler/ReconcilerImpl.kt

The `lastRun` variable was being updated every 5 minutes by the slim reconciler run, meaning the delta would never grow large enough to trigger the full reconciler run.
Closes #320

use 2 timestamps to derive the 2 deltas

---

gradle/libs.versions.toml

* container-core: removal of unused and problematic jersey lib to fix json (de)serialization issues.
* vdi-json: jackson version update
* vdi-component-common: 2 types were missing explicit type delegation that unconfigured jackson couldn't find, but all other types have explicit definitions so I added the missing 2.

Stop using jersey's jackson filter instead of ours.
